name: Supernova <> Figma Token sync
on:
  # Any branch you want
  push:
    branches:
      - feature/design-tokens
  workflow_dispatch:

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3

      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova
        run: >
          supernova sync-tokens \
          --apiKey="${{ secrets.SUPERNOVA_API_KEY }}" \
          --designSystemId="27354" \
          --tokenDirPath="${{ github.workspace }}/design-tokens" \
          --configFilePath="${{ github.workspace }}/supernova.settings.json" \
