name: "Design Tokens Sync (Production)"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3
      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova
        run: |
          supernova sync-tokens \
          --apiKey="${{ secrets.SUPERNOVA_API_KEY }}" \
          --designSystemId="24475" \
          --tokenDirPath="${{ github.workspace }}/design-tokens" \
          --configFilePath="${{ github.workspace }}/supernova.settings.prod.json"

      - name: Set current date as env variable
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV && echo "CURRENT_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
        if: always()
