name: "Design Tokens Sync (Staging)"
run-name: Staging build for ${{ github.ref_name }} by @${{ github.actor }}
on: [pull_request, workflow_dispatch]

jobs:
  sync_tokens:
    name: Tokens Studio > Supernova
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova
        run: |
          supernova sync-tokens \
          --apiKey="${{ secrets.SUPERNOVA_API_KEY }}" \
          --designSystemId="27354" \
          --tokenDirPath="${{ github.workspace }}/design-tokens" \
          --configFilePath="${{ github.workspace }}/supernova.settings.staging.json"
  
  build_tokens:
    name: Build JSON Tokens
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: npm run build:tokens

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Token JSON files
          commit_options: "--no-verify"
          commit_user_name: "Matthew Morek"
          commit_user_email: "hi@matthewmorek.com"
          commit_author: "Matthew Morek <hi@matthewmorek.com>"
          file_pattern: "dist/*.json"
